ASP/Homeworks/ASP_NET_InternetShop/GameStoreUI/Areas/Admin/Models/Genres/CreateGenreViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace GameStoreUI.Areas.Admin.Models.Genres
{
    public class CreateGenreViewModel
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Name is required")]
        public string Name { get; set; }
    }
}

ASP/Homeworks/ASP_NET_InternetShop/GameStoreUI/Areas/Admin/Models/Genres/EditGenreViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace GameStoreUI.Areas.Admin.Models.Genres
{
    public class EditGenreViewModel
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Name is required")]
        public string Name { get; set; }
    }
}

ASP/Homeworks/ASP_NET_InternetShop/GameStoreUI/Areas/Admin/Models/Genres/GenreViewModel.cs
namespace GameStoreUI.Areas.Admin.Models.Genres
{
    public class GenreViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int GamesCount { get; set; }
    }
}

ASP/Homeworks/ASP_NET_InternetShop/GameStoreUI/Areas/Admin/Controllers/GenresController.cs
using AutoMapper;
using GameStoreBLL.Services.Abstraction;
using GameStoreDAL.Entities;
using GameStoreUI.Areas.Admin.Models.Genres;
using System.Collections.Generic;
using System.Web.Mvc;

namespace GameStoreUI.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class GenresController : Controller
    {
        private readonly IGenreService genreService;
        private readonly IMapper mapper;

        public GenresController(IGenreService genreService, IMapper mapper)
        {
            this.genreService = genreService;
            this.mapper = mapper;
        }

        [AllowAnonymous]
        public ActionResult Index()
        {
            var genres = genreService.GetAllGenres();

            var models = mapper.Map<IEnumerable<Genre>, IEnumerable<GenreViewModel>>(genres);

            return View(models);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(CreateGenreViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return Create();
            }
            var genre = mapper.Map<CreateGenreViewModel, Genre>(model);

            genreService.CreateGenre(genre);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var genre = genreService.GetGenreById(id);

            var model = mapper.Map<Genre, EditGenreViewModel>(genre);

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(EditGenreViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return Edit(model.Id);
            }

            var genre = mapper.Map<EditGenreViewModel, Genre>(model);

            genreService.UpdateGenre(genre);

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            genreService.DeleteGenre(id);

            return RedirectToAction(nameof(Index));
        }
    }
}

ASP/Homeworks/ASP_NET_InternetShop/GameStoreUI/Areas/Admin/Views/Genres/Partial/GenresPartial.cshtml
@model IEnumerable<GameStoreUI.Areas.Admin.Models.Genres.GenreViewModel>
@using Microsoft.AspNet.Identity
@{
    var isAdmin = User.IsInRole("Admin");
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            Games Count
        </th>
        @if (isAdmin)
        {
            <th>
                Actions
            </th>
        }
    </tr>

    @foreach (var item in Model)
    {
        using (@Html.BeginForm("Delete", "Genres", new { area = "Admin", id = item.Id }, FormMethod.Post))
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.GamesCount)
                </td>
                @if (isAdmin)
                {
                    <td>
                        @Html.ActionLink("Edit", "Edit", "Genres", new { area = "Admin", id = item.Id }, new { @class = "btn-sm btn-warning" })
                        <input type="submit" value="Delete" class="btn-sm btn-danger" />
                    </td>
                }
            </tr>
        }

    }

</table>

ASP/Homeworks/ASP_NET_InternetShop/GameStoreUI/Areas/Admin/Views/Genres/Partial/Sidebar.cshtml
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
        @*<img src="dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">*@
        <span class="brand-text font-weight-light">GAMES STORE</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar os-host os-theme-light os-host-overflow os-host-overflow-y os-host-resize-disabled os-host-scrollbar-horizontal-hidden os-host-transition">
        <div class="os-resize-observer-host observed"><div class="os-resize-observer" style="left: 0px; right: auto;"></div></div><div class="os-size-auto-observer observed" style="height: calc(100% + 1px); float: left;"><div class="os-resize-observer"></div></div><div class="os-content-glue" style="margin: 0px -8px;"></div><div class="os-padding">
            <div class="os-viewport os-viewport-native-scrollbars-invisible">
                <div class="os-content" style="padding: 0px 8px; height: 100%; width: 100%;">
                    <!-- Sidebar Menu -->
                    <nav class="mt-2">
                        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                            <li class="nav-item">
                                <p>
                                    @Html.ActionLink("Create New", "Create", "Genres", new { @class = "btn btn-primary" })
                                </p>
                            </li>
                        </ul>
                    </nav>
                    <!-- /.sidebar-menu -->
                </div>
            </div>
        </div><div class="os-scrollbar os-scrollbar-horizontal os-scrollbar-unusable os-scrollbar-auto-hidden"><div class="os-scrollbar-track"><div class="os-scrollbar-handle" style="width: 100%; transform: translate(0px, 0px);"></div></div></div><div class="os-scrollbar os-scrollbar-vertical os-scrollbar-auto-hidden"><div class="os-scrollbar-track"><div class="os-scrollbar-handle" style="height: 43.5583%; transform: translate(0px, 0px);"></div></div></div><div class="os-scrollbar-corner"></div>
    </div>
    <!-- /.sidebar -->
</aside>