ASP/Homeworks/StoreCS/StoreCS/Areas/Admin/Models/CreateCategoryViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace StoreCS.Areas.Admin.Models
{
    public class CreateCategoryViewModel
    {
        [Required(ErrorMessage = "Category name is required")]
        public string Name { get; set; }
    }
}

ASP/Homeworks/StoreCS/StoreCS/Areas/Admin/Models/CreateRoleViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace StoreCS.Areas.Admin.Models
{
    public class CreateRoleViewModel
    {
        [Required(ErrorMessage = "Role name is required")]
        public string Name { get; set; }
    }
}

ASP/Homeworks/StoreCS/StoreCS/Areas/Admin/Controllers/AdminPanelController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using StoreCS.Areas.Admin.Models;
using StoreCS.Entity;
using StoreCS.Helpers;
using StoreCS.Models;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace StoreCS.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminPanelController : Controller
    {
        private readonly ApplicationDbContext context;
        private readonly ApplicationUserManager userManager;
        private readonly RoleManager<IdentityRole> roleManager;
        public AdminPanelController()
        {
            context = new ApplicationDbContext();
            userManager = new ApplicationUserManager(new UserStore<ApplicationUser>(context));
            roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(context));
        }
        public ActionResult Index()
        {
            var adminModel = ModelHelper.GetAdminViewModel(context, roleManager);

            return View(adminModel);
        }

        [HttpPost]
        public async Task<ActionResult> Index(string id, string role)
        {
            var user = context.Users
                              .FirstOrDefault(x => x.Id.Equals(id));

            var currentRoleId = context.Set<IdentityUserRole>()
                                       .FirstOrDefault(x => x.UserId.Equals(id))
                                       .RoleId;

            var currentRole = roleManager.FindById(currentRoleId).Name;

            var removeResult = await userManager.RemoveFromRoleAsync(user.Id, currentRole);

            var addResult = await userManager.AddToRoleAsync(user.Id, role);

            var adminModel = ModelHelper.GetAdminViewModel(context, roleManager);

            return View(adminModel);
        }

        [HttpGet]
        public ActionResult CreateRole()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateRole(CreateRoleViewModel model)
        {
            var role = new IdentityRole(model.Name);

            var result = roleManager.Create(role);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public ActionResult CreateCategory()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateCategory(CreateCategoryViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var category = new Category { Name = model.Name };

            context.Categories.Add(category);

            context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public ActionResult ListRoles()
        {
            var models = ModelHelper.GetRoleViewModels(context);

            return View(models);
        }

        [HttpPost]
        public async Task<ActionResult> RemoveRole(string id)
        {
            var role = await roleManager.FindByIdAsync(id);

            var deleteResult = await roleManager.DeleteAsync(role);

            return RedirectToAction(nameof(ListRoles));
        }

        [HttpGet]
        public ActionResult ListCategories()
        {
            var models = ModelHelper.GetCategoryViewModels(context);

            return View(models);
        }

        [HttpPost]
        public async Task<ActionResult> RemoveCategory(int id)
        {
            var category = context.Categories
                                  .FirstOrDefault(x => x.Id.Equals(id));

            context.Categories
                   .Remove(category);

            var res = await context.SaveChangesAsync();

            return RedirectToAction(nameof(ListCategories));
        }
    }
}

ASP/Homeworks/StoreCS/StoreCS/Areas/Admin/Views/AdminPanel/CreateCategory.cshtml
@model StoreCS.Areas.Admin.Models.CreateCategoryViewModel

@{
    ViewBag.Title = "CreateCategory";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create Category</h2>

@using (Html.BeginForm("CreateCategory", "AdminPanel", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-warning" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ASP/Homeworks/StoreCS/StoreCS/Areas/Admin/Views/AdminPanel/CreateRole.cshtml
@model StoreCS.Areas.Admin.Models.CreateRoleViewModel

@{
    ViewBag.Title = "CreateRole";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create Role</h2>

@using (Html.BeginForm("CreateRole", "AdminPanel", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-warning" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ASP/Homeworks/StoreCS/StoreCS/Areas/Admin/Views/AdminPanel/Index.cshtml
@model StoreCS.Models.AdminViewModel
@{
    ViewBag.Title = "Admin";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    @Html.AntiForgeryToken()
    <table class="table">
        <tr>
            <th>
                Email
            </th>

            <th>
                Roles
            </th>

            <th>
                Action
            </th>
        </tr>
        @foreach (var user in Model.Users)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => user.Email)
                </td>
                @using (Html.BeginForm("Index", "AdminPanel", new { id = user.Id }, FormMethod.Post))
                {
                    <td>
                        <select name="role" class="form-control">
                            @foreach (var role in Model.Roles)
                            {
                                if (user.Role.Equals(role))
                                {
                                    <option selected>@role</option>
                                }
                                else
                                {
                                    <option>@role</option>

                                }
                            }
                        </select>
                    </td>
                    <td>
                        <button type="submit" class="btn-sm btn-success">Set</button>
                    </td>
                }
            </tr>
        }
    </table>
    
    
    @Html.ActionLink("List categories", "ListCategories", null, new { @class = "btn-sm btn-warning" })
    @Html.ActionLink("List roles", "ListRoles", null, new { @class = "btn-sm btn-warning" })

</div>

ASP/Homeworks/StoreCS/StoreCS/Areas/Admin/Views/AdminPanel/ListCategories.cshtml
@model IEnumerable<StoreCS.Areas.Admin.Models.CategoryViewModel>

@{
    ViewBag.Title = "ListCategories";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Categories</h2>

<div class="container">
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                Action
            </th>
        </tr>

        @foreach (var role in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => role.Name)
                </td>
                @using (Html.BeginForm("RemoveCategory", "AdminPanel", new { id = role.Id }, FormMethod.Post))
                {
                    <td>
                        <input type="submit" value="Delete" class="btn-sm btn-danger" />
                    </td>
                }

            </tr>
        }

    </table>

    @Html.ActionLink("Create category", "CreateCategory", null, new { @class = "btn-sm btn-warning" })
</div>

ASP/Homeworks/StoreCS/StoreCS/Areas/Admin/Views/AdminPanel/ListRoles.cshtml
@model IEnumerable<StoreCS.Areas.Admin.Models.RoleViewModel>

@{
    ViewBag.Title = "ListRoles";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Roles</h2>
<div class="container">
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                Action
            </th>
        </tr>

        @foreach (var role in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => role.Name)
                </td>
                @using (Html.BeginForm("RemoveRole", "AdminPanel", new { id = role.Id }, FormMethod.Post))
                {
                    <td>
                        <input type="submit" value="Delete" class="btn-sm btn-danger"/>
                    </td>
                }

            </tr>
        }

    </table>

    @Html.ActionLink("Create role", "CreateRole", null, new { @class = "btn-sm btn-warning" })
</div>