ASP/Homeworks/ASP_NET_InternetShop/GameStoreUI/Areas/Admin/Models/Developers/CreateDeveloperViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace GameStoreUI.Areas.Admin.Models.Developers
{
    public class CreateDeveloperViewModel
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Name is required")]
        public string Name { get; set; }
    }
}

ASP/Homeworks/ASP_NET_InternetShop/GameStoreUI/Areas/Admin/Models/Developers/DeveloperViewModel.cs
namespace GameStoreUI.Areas.Admin.Models.Developers
{
    public class DeveloperViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int GamesCount { get; set; }
    }
}

ASP/Homeworks/ASP_NET_InternetShop/GameStoreUI/Areas/Admin/Models/Developers/EditDeveloperViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace GameStoreUI.Areas.Admin.Models.Developers
{
    public class EditDeveloperViewModel
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Name is required")]
        public string Name { get; set; }
    }
}

ASP/Homeworks/ASP_NET_InternetShop/GameStoreUI/Areas/Admin/Controllers/DevelopersController.cs
using AutoMapper;
using GameStoreBLL.Services.Abstraction;
using GameStoreDAL.Entities;
using GameStoreUI.Areas.Admin.Models.Developers;
using System.Collections.Generic;
using System.Web.Mvc;

namespace GameStoreUI.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class DevelopersController : Controller
    {
        private readonly IDeveloperService developerService;
        private readonly IMapper mapper;

        public DevelopersController(IDeveloperService developerService, IMapper mapper)
        {
            this.developerService = developerService;
            this.mapper = mapper;
        }

        [AllowAnonymous]
        public ActionResult Index()
        {
            var developers = developerService.GetAllDevelopers();

            var models = mapper.Map<IEnumerable<Developer>, IEnumerable<DeveloperViewModel>>(developers);

            return View(models);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(CreateDeveloperViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return Create();
            }
            var developer = mapper.Map<CreateDeveloperViewModel, Developer>(model);

            developerService.CreateDeveloper(developer);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var developer = developerService.GetDeveloperById(id);

            var model = mapper.Map<Developer, EditDeveloperViewModel>(developer);

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(EditDeveloperViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return Edit(model.Id);
            }

            var developer = mapper.Map<EditDeveloperViewModel, Developer>(model);

            developerService.UpdateDeveloper(developer);

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            developerService.DeleteDeveloper(id);

            return RedirectToAction(nameof(Index));
        }
    }
}

ASP/Homeworks/ASP_NET_InternetShop/GameStoreUI/Areas/Admin/Views/Developers/Create.cshtml
@model GameStoreUI.Areas.Admin.Models.Developers.CreateDeveloperViewModel

@{
    ViewBag.Title = "Create developer";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Create developer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "Developers", new { @class = "btn btn-primary" })
</div>

ASP/Homeworks/ASP_NET_InternetShop/GameStoreUI/Areas/Admin/Views/Developers/Edit.cshtml
@model GameStoreUI.Areas.Admin.Models.Developers.EditDeveloperViewModel

@{
    ViewBag.Title = "Edit developer";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Edit developer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "Developers", new { @class = "btn btn-primary" })
</div>

ASP/Homeworks/ASP_NET_InternetShop/GameStoreUI/Areas/Admin/Views/Developers/Index.cshtml
@model IEnumerable<GameStoreUI.Areas.Admin.Models.Developers.DeveloperViewModel>
@using Microsoft.AspNet.Identity
@{
    var isAdmin = User.IsInRole("Admin");
}
@{
    ViewBag.Title = "Developers";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

@if (isAdmin)
{
    Html.RenderPartial("Partial/Sidebar");
}
<div class="content-wrapper">
    <div class="container my-container" id="developers">
        @{
            Html.RenderPartial("Partial/DevelopersPartial", Model);
        }
    </div>
</div>